# Logging LEVEL Setting
logging:
  level:
    ezfarm: DEBUG
    org.springframework:
      web: WARN
      security: WARN
      messaging: WARN

    jdbc: WARN
    resultset: WARN

server:
  port: 8100

Globals.DbType: h2

spring:
  h2:
    console:
      enabled: true
      path: /ezfarmdb

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/data/ezfarmdb # ./ Project root
      username: sa
      password:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
#      connection-init-sql: data.sql
      
mybatis:
  config-location: classpath*:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml
      