spring:
  h2:
    console:
      enabled: true
      path: /ezfarmdb

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:~/data/ezfarmdb # Project root (상대경로를 추첨, 절대경로는 Exception)
      username: sa
      password: 
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000
    data: classpath*:data.sql # 쉼표로 여려개 구분할 수 있음. ex) classpath:data1.sql, classpath:data2.sq
      
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
      