DROP TABLE IF EXISTS EZ_BIZ_TEAM;
CREATE TABLE EZ_BIZ_TEAM
(
    BID integer NOT NULL, -- BIZ ID 
    NAME varchar(255) not null,
    primary key(BID)
);

DROP TABLE IF EXISTS EZ_PROJ_CODE;
CREATE TABLE EZ_PROJ_CODE
(
    BID integer NOT NULL,
    USED_DT DATETIME NOT NULL,
    NAME varchar(255) not null
);

INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (0, 'IIS사업본부');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (1, '농업정보화사업본부');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (2, '시스템사업본부');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (3, '축산연구소');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (4, '스마트팜연구소');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (5, '스마트유통사업본부');
INSERT INTO EZ_BIZ_TEAM (BID, NAME) VALUES (6, '블록체인사업본부');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_산림청');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SKHy_Cloud');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SKT DaTalent_MA');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_관세청');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_삼성닷컴');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_LG CNS');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_삼성중공업');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SKT DaTalent_고도화');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_Subscription');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_Pre Sale');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_롯데쇼핑_CRM');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_현대 차세대 보안 고도화');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SKT T-View 고도화');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_관세청 2차');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SKHy_Log 통합');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_컨설팅용역');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_교통주차');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (0, SYSDATE, '19_IIS_SK케미컬_로그분석');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_강원연합_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_안성과수_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_APC유지');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_막걸리IOT_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_로컬푸드');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_완주유지');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_내면농협');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_송원APC');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (1, SYSDATE, '19_농업정보화_법인연합회');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_검역유지보수');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_에그릭스운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_AT운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_에그릭스개발');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_현대백화점');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_산란계');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_식물검역개발');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (2, SYSDATE, '19_시스템_방역본부개발');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_피그플랜');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_피그플랜광고');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_입력대행');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_피그비전');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_SAAS');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_머신러닝_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_예측모델_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_양돈빅데이터');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_재난형동물질병');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_스마트돈사_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_PRDC_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_GSIP_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (3, SYSDATE, '19_축산_넙치영상분석');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_노지과제_연구');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_스마트팜교육장');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_TAP KIT');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_TAP KIT-P');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_PFC');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (4, SYSDATE, '19_스마트팜_PFC 과제');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_경기도운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_경기농정운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_경기시군운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_아산유지보수');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_경기도개발');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_가락24운영');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (5, SYSDATE, '19_스마트유통_유통사업');

INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (6, SYSDATE, '19_블록체인_공통');
INSERT INTO EZ_PROJ_CODE (BID, USED_DT, NAME) VALUES (6, SYSDATE, '19_블록체인_블록체인과제_연구');